services:
  db:
    image: mysql:oraclelinux9
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: managementPersonalFinance
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql

volumes:
  db_data: